apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: nhc-config
  namespace: open-cluster-management-policies
spec:
  disabled: false
  remediationAction: enforce
  dependencies:
    - apiVersion: policy.open-cluster-management.io/v1
      kind: Policy
      name: nhc-operators
      namespace: open-cluster-management-policies
      compliance: Compliant
    - apiVersion: policy.open-cluster-management.io/v1
      kind: Policy
      name: nhc-snr-ready
      namespace: open-cluster-management-policies
      compliance: Compliant
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: nhc-config
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: self-node-remediation.medik8s.io/v1alpha1
                kind: SelfNodeRemediationConfig
                metadata:
                  name: self-node-remediation-config
                  namespace: openshift-workload-availability
                spec:
                  apiCheckInterval: 15s
                  apiServerTimeout: 5s
                  hostPort: 30001
                  isSoftwareRebootEnabled: true
                  maxApiErrorThreshold: 3
                  minPeersForRemediation: 1
                  peerApiServerTimeout: 5s
                  peerDialTimeout: 5s
                  peerRequestTimeout: 7s
                  peerUpdateInterval: 15m
                  watchdogFilePath: /dev/watchdog
            - complianceType: musthave
              objectDefinition:
                apiVersion: remediation.medik8s.io/v1alpha1
                kind: NodeHealthCheck
                metadata:
                  name: control-plane-node-health-check
                spec:
                  selector:
                    matchExpressions:
                      - key: node-role.kubernetes.io/control-plane
                        operator: Exists
                  maxUnhealthy: 1
                  unhealthyConditions:
                    - type: Ready
                      status: "False"
                      duration: 300s
                    - type: Ready
                      status: "Unknown"
                      duration: 300s
                  remediationTemplate:
                    apiVersion: self-node-remediation.medik8s.io/v1alpha1
                    kind: SelfNodeRemediationTemplate
                    name: self-node-remediation-automatic-strategy-template
                    namespace: openshift-workload-availability
            - complianceType: musthave
              objectDefinition:
                apiVersion: remediation.medik8s.io/v1alpha1
                kind: NodeHealthCheck
                metadata:
                  name: worker-node-health-check
                spec:
                  selector:
                    matchExpressions:
                      - key: node-role.kubernetes.io/worker
                        operator: Exists
                  maxUnhealthy: 1
                  unhealthyConditions:
                    - type: Ready
                      status: "False"
                      duration: 300s
                    - type: Ready
                      status: "Unknown"
                      duration: 300s
                  remediationTemplate:
                    apiVersion: self-node-remediation.medik8s.io/v1alpha1
                    kind: SelfNodeRemediationTemplate
                    name: self-node-remediation-automatic-strategy-template
                    namespace: openshift-workload-availability
