apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: node-maintenance
  namespace: open-cluster-management-policies
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: node-maintenance
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: nmo-operator
