apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - dell-csm-operator.yaml
  - dell-csm-powerflex-prerequisites.yaml
  - dell-csm-powerflex-secret.yaml
  - dell-csm-powerflex.yaml
  - dell-csm-powerflex-storage.yaml
