apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: virt-operator
  namespace: open-cluster-management-policies
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: openshift-cnv-namespace
        spec:
          remediationAction: enforce
          severity: medium
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: openshift-cnv
                  labels:
                    openshift.io/cluster-monitoring: "true"
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: openshift-virtualization
        spec:
          complianceType: musthave
          remediationAction: enforce
          severity: medium
          upgradeApproval: None
          versions:
            - kubevirt-hyperconverged-operator.v4.21.16
          operatorGroup:
            name: kubevirt-hyperconverged-group
            namespace: openshift-cnv
            targetNamespaces:
              - openshift-cnv
          subscription:
            channel: stable
            name: kubevirt-hyperconverged
            namespace: openshift-cnv
            source: redhat-operators
            sourceNamespace: openshift-marketplace
            startingCSV: kubevirt-hyperconverged-operator.v4.21.16
