apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: mtv
  namespace: open-cluster-management-policies
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            capability.openshift-virtualization: "true"
            capability.mtv: "true"
