apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: node-maintenance
  namespace: open-cluster-management-policies
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            capability.node-maintenance: "true"
