apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: logging-operator
  namespace: open-cluster-management-policies
spec:
  disabled: false
  remediationAction: enforce
  dependencies:
    - apiVersion: policy.open-cluster-management.io/v1
      kind: Policy
      name: loki-operator
      namespace: open-cluster-management-policies
      compliance: Compliant
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: logging-workload-namespace
        spec:
          remediationAction: enforce
          severity: medium
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: openshift-logging
                  annotations:
                    openshift.io/node-selector: ""
                  labels:
                    openshift.io/cluster-monitoring: "true"
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: logging-cluster-logging-operator
        spec:
          complianceType: musthave
          remediationAction: enforce
          severity: medium
          upgradeApproval: None
          versions:
            - cluster-logging.v6.6.1
          operatorGroup:
            name: cluster-logging
            namespace: openshift-logging
          subscription:
            channel: stable-6.6
            name: cluster-logging
            namespace: openshift-logging
            source: redhat-operators
            sourceNamespace: openshift-marketplace
            startingCSV: cluster-logging.v6.6.1
