apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: loki-operator
  namespace: open-cluster-management-policies
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: logging-loki-operator-namespace
        spec:
          remediationAction: enforce
          severity: medium
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: openshift-operators-redhat
                  labels:
                    openshift.io/cluster-monitoring: "true"
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: logging-loki-operator
        spec:
          complianceType: musthave
          remediationAction: enforce
          severity: medium
          upgradeApproval: None
          versions:
            - loki-operator.v6.6.1
          operatorGroup:
            name: loki-operator
            namespace: openshift-operators-redhat
          subscription:
            channel: stable-6.6
            name: loki-operator
            namespace: openshift-operators-redhat
            source: redhat-operators
            sourceNamespace: openshift-marketplace
            startingCSV: loki-operator.v6.6.1
